load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "adapter",
    srcs = [
        "adapter.go",
        "profile.go",
    ],
    importpath = "github.com/martian-lang/martian/martian/adapter",
    visibility = ["//visibility:public"],
    deps = [
        "//martian/core",
        "//martian/util",
    ],
)

go_test(
    name = "adapter_test",
    srcs = select({
        "@io_bazel_rules_go//go/platform:windows": [
            "adapter_windows_test.go",
        ],
        "//conditions:default": [],
    }),
    embed = [":adapter"],
)

# Backwards compat for what gazelle used to call this target.
alias(
    name = "go_default_library",
    actual = "adapter",
    visibility = ["//visibility:public"],
)
